### ISSUE TITLE
PennyLane v0.28.0 introduces breaking changes

### ISSUE THREAD

**Issue by yitchen-tim** [aws/amazon-braket-pennylane-plugin-python#126]
There are [breaking change](https://docs.pennylane.ai/en/stable/development/release_notes.html) introduced in Pennylane v0.28.0. Python3.7 is no longer supported, and MeasurementProcess is changed in how it's used. If you are using Python3.7, or if you encounter errors about MeasurementProcess, you can try pin the PennyLane version to lower than v0.28.0:
```
pip install pennylane==0.27.0
```

**Comment by christianbmadsen** [comment]
Closing this issue as we have deprecated support for Python 3.7 and moved to Python 3.9 as our default version in Braket.
