### ISSUE TITLE
Cannot launch Rigetti

### ISSUE THREAD

**Issue by Haoxiang-Wang** [aws/amazon-braket-pennylane-plugin-python#127]
I try to launch a Rigetti GPU following this example
https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/5ead8b684d76a3fd7bca3d858b9f7ae7f4a3480a/example.py#L26-L28

But I encounter the `Device does not exist` error, even though I put `device_arn='arn:aws:braket:us-west-1::device/qpu/rigetti/Aspen-M-2'` in the function input:
```bash
~/opt/anaconda3/lib/python3.9/site-packages/pennylane/__init__.py in device(name, *args, **kwargs)
    335         return dev
    336 
--> 337     raise DeviceError("Device does not exist. Make sure the required plugin is installed.")
    338 
    339 

DeviceError: Device does not exist. Make sure the required plugin is installed.
```

I think it's because the device name "braket.rigetti" is not valid (or not supported yet?). Could you give some instructions on launching jobs to Rigetti QPUs with this braket-pennylane plugin?

**Comment by virajvchaudhari** [comment]
Hello @Haoxiang-Wang, 

Thanks for reaching out. We currently don't support the keyword `braket.rigetti`. Could you please try running the circuit with the following and let us know if that works for you.  

```
dev_qpu = qml.device("braket.aws_qubit",
wires=2,
device_arn='arn:aws:braket:us-west-1::device/qpu/rigetti/Aspen-M-2',
s3_destination_folder=s3, 
poll_timeout_seconds=1800, 
shots=10000)
```

**Comment by Haoxiang-Wang** [comment]
Hi @virajvchaudhari , thank you for the instruction! The device name "braket.aws_qubit" doesn't work (leading to the same `DeviceError: Device does not exist.`, but changing it to **"braket.aws.qubit"** makes the code work without error!

**Comment by virajvchaudhari** [comment]
Yes, @Haoxiang-Wang, I meant `braket.aws.qubit`, updated the instructions. I am glad it worked for you. Feel free to re-open if you face further issues.
