### ISSUE TITLE
pennylane>=0.15 for amazon-braket-pennylane-plugin

### ISSUE THREAD

**Issue by santoshkumarradha** [aws/amazon-braket-pennylane-plugin-python#65]
**Describe the bug**
pennylane-lightning 0.15.1 requires pennylane>=0.15, but you have pennylane 0.14.1 which is incompatible.
amazon-braket-pennylane-plugin 1.1.1 requires pennylane==0.14.1, but you have pennylane 0.15.1 which is incompatible.

**To reproduce**
pip install pennylane-lightning
pip install amazon-braket-pennylane-plugin

**Expected behavior**
Both needs to be version compatible

**Additional context**
Since some of the features are incompatible between pennylane>=0.15 and pennylane==0.14., it seems like one definitely needs to have Braket plugin support pennylane==0.15

**Comment by speller26** [comment]
Currently being worked on in #62

**Comment by santoshkumarradha** [comment]
Thanks for that info :D
