### ISSUE TITLE
Device tracker support

### ISSUE THREAD

**Issue by albi3ro** [aws/amazon-braket-pennylane-plugin-python#74]
In the upcoming PennyLane v0.17.0 release, we will be introducing a [`Tracker`](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.Tracker.html). This tracker introduces the ability for devices to store arbitrary information on each execution and batch execution and lets the users interact with that information with a user-provided `callback` function.

While on standard PennyLane devices, we will track executions, shots, batches, and batch length, the tracker allows for storage of arbitrary keyword-value pairs of information. So the braket plugin can store task metadata and additional relevant details like price or total simulation time.

You can find additional information on incorporating the tracker in the documentation section on [Device tracker support](https://pennylane.readthedocs.io/en/latest/development/plugins.html#device-tracker-support).

I developed a prototype [on my own fork](https://github.com/albi3ro/amazon-braket-pennylane-plugin-python/tree/add-tracker), that I can submit as a PR.

**Comment by wrasmuss** [comment]
@albi3ro Since you've created a prototype, opening a PR seems like a great idea. It will certainly help us move the conversation forward.
