### ISSUE TITLE
Braket plugin import error for PennyLane version 0.23

### ISSUE THREAD

**Issue by licedric** [aws/amazon-braket-pennylane-plugin-python#96]
**Describe the bug**
The Braket plugin for PennyLane will fail with import errors due to the renaming in https://github.com/PennyLaneAI/pennylane/pull/2329.

**To reproduce**
Install PennyLane with the latest dev version and the Braket-PennyLane plugin, and try to import the Braket device.

**Expected behavior**
There should be no import errors.

**Screenshots or logs**
https://github.com/PennyLaneAI/plugin-test-matrix/runs/6070544197?check_suite_focus=true

**System information**

**Additional context**
https://github.com/PennyLaneAI/pennylane/pull/2329

**Comment by krneta** [comment]
This issue has been resolved by the related merge, above.
